### ISSUE TITLE
[Request]  3주차 - [BOOKMARK] 즐겨찾기 추가 예외처리 시 게시물 조회 메소드 필요

### ISSUE THREAD

**Issue by Dylan-SonJungin** [cca-ffodregamdi/running-hi-back#91]
🙏필요한 기능 설명
-
- 즐겨찾기 추가 시 존재하지 않는 게시물 예외처리 할 때 게시물 find 메소드 필요합니다!

⭐필요 도메인
-
- user_post
- admin_post

👪담당자
-
 @numerical43 @Subak-Uncle

**Comment by fakerdeft** [comment]
리퀘스트 첨보네요 신기합니다!!

**Comment by Subak-Uncle** [comment]
네 해당부분 추가하면서 질문사항 있으면 말씀드릴게요!
